export const fruits = [
	{ name: "grape", icon: "🍇", color: "purple" },
	{ name: "melon", icon: "🍈", color: "green" },
	{ name: "watermelon", icon: "🍉", color: "red" },
	{ name: "tangerine", icon: "🍊", color: "orange" },
	{ name: "lemon", icon: "🍋", color: "yellow" },
	{ name: "lime", icon: "🍋‍🟩", color: "limegreen" },
	{ name: "banana", icon: "🍌", color: "yellow" },
	{ name: "pineapple", icon: "🍍", color: "orange" },
	{ name: "mango", icon: "🥭", color: "orange" },
	{ name: "red apple", icon: "🍎", color: "red" },
	{ name: "green apple", icon: "🍏", color: "green" },
	{ name: "pear", icon: "🍐", color: "green" },
	{ name: "peach", icon: "🍑", color: "orange" },
	{ name: "cherry", icon: "🍒", color: "red" },
	{ name: "strawberry", icon: "🍓", color: "red" },
	{ name: "blueberry", icon: "🫐", color: "blue" },
	{ name: "kiwi", icon: "🥝", color: "green" },
	{ name: "tomatoe", icon: "🍅", color: "red" },
	{ name: "olive", icon: "🫒", color: "green" },
	{ name: "coconut", icon: "🥥", color: "brown" },
];
