export const fruits = [
	{ name: "grape", icon: "🍇" },
	{ name: "melon", icon: "🍈" },
	{ name: "watermelon", icon: "🍉" },
	{ name: "tangerine", icon: "🍊" },
	{ name: "lemon", icon: "🍋" },
	{ name: "lime", icon: "🍋‍🟩" },
	{ name: "banana", icon: "🍌" },
	{ name: "pineapple", icon: "🍍" },
	{ name: "mango", icon: "🥭" },
	{ name: "red apple", icon: "🍎" },
	{ name: "green apple", icon: "🍏" },
	{ name: "pear", icon: "🍐" },
	{ name: "peach", icon: "🍑" },
	{ name: "cherry", icon: "🍒" },
	{ name: "strawberry", icon: "🍓" },
	{ name: "blueberry", icon: "🫐" },
	{ name: "kiwi", icon: "🥝" },
	{ name: "tomatoe", icon: "🍅" },
	{ name: "olive", icon: "🫒" },
	{ name: "coconut", icon: "🥥" },
];
